version: '3.8'

services:
  django_api:
    build: . 
    container_name: django_api
    command: >
      sh -c "while ! pg_isready -h db -U trafficuser; do sleep 1; done &&
      python manage.py migrate --no-input &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      -  db

  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data: